import moment from 'moment'

export const proyects = [{
    id: 'p1',
    name:'Proyect 1',
    status: 'todo',
    invoice: '100',
    startDate: moment("2021-03-15").valueOf(),
    endDate: moment("2021-03-19").valueOf(),
    color: 'green',
    description: 'This is my proyect fixure 1',
}, {
    id: 'p2',
    name:'Proyect 2',
    status: 'doing',
    invoice: '200',
    startDate: moment("2021-03-20").valueOf(),
    endDate: moment("2021-03-24").valueOf(),
    color: 'red',
    description: 'This is my proyect fixure 2',
}, {
    id: 'p3',
    name:'Proyect 3',
    status: 'done',
    invoice: '300',
    startDate: moment("2021-03-25").valueOf(),
    endDate: moment("2021-03-29").valueOf(),
    color: 'blue',
    description: 'This is my proyect fixure 3',
}]

export const paginationProyects = [{
    id: 'p1',
    name:'Proyect 1',
    status: 'todo',
    invoice: '100',
    startDate: moment("2021-03-25").valueOf(),
    endDate: moment("2021-03-29").valueOf(),
    color: 'green',
    description: 'This is my proyect fixure 1',
}, {
    id: 'p2',
    name:'Proyect 2',
    status: 'doing',
    invoice: '200',
    startDate: moment("2021-03-25").valueOf(),
    endDate: moment("2021-03-29").valueOf(),
    color: 'red',
    description: 'This is my proyect fixure 2',
}, {
    id: 'p3',
    name:'Proyect 3',
    status: 'done',
    invoice: '300',
    startDate: moment("2021-03-25").valueOf(),
    endDate: moment("2021-03-29").valueOf(),
    color: 'blue',
    description: 'This is my proyect fixure 3',
}, {
    id: 'p4',
    name:'Proyect 4',
    status: 'todo',
    invoice: '100',
    startDate: moment("2021-03-25").valueOf(),
    endDate: moment("2021-03-29").valueOf(),
    color: 'green',
    description: 'This is my proyect fixure 4',
}, {
    id: 'p5',
    name:'Proyect 5',
    status: 'doing',
    invoice: '200',
    startDate: moment("2021-03-25").valueOf(),
    endDate: moment("2021-03-29").valueOf(),
    color: 'red',
    description: 'This is my proyect fixure 5',
}, {
    id: 'p6',
    name:'Proyect 6',
    status: 'done',
    invoice: '300',
    startDate: moment("2021-03-25").valueOf(),
    endDate: moment("2021-03-29").valueOf(),
    color: 'blue',
    description: 'This is my proyect fixure 6',
}, {
    id: 'p7',
    name:'Proyect 7',
    status: 'todo',
    invoice: '100',
    startDate: moment("2021-03-25").valueOf(),
    endDate: moment("2021-03-29").valueOf(),
    color: 'green',
    description: 'This is my proyect fixure 7',
}, {
    id: 'p8',
    name:'Proyect 8',
    status: 'doing',
    invoice: '200',
    startDate: moment("2021-03-25").valueOf(),
    endDate: moment("2021-03-29").valueOf(),
    color: 'red',
    description: 'This is my proyect fixure 8',
}, {
    id: 'p9',
    name:'Proyect 9',
    status: 'done',
    invoice: '300',
    startDate: moment("2021-03-25").valueOf(),
    endDate: moment("2021-03-29").valueOf(),
    color: 'blue',
    description: 'This is my proyect fixure 9',
}, {
    id: 'p10',
    name:'Proyect 10',
    status: 'todo',
    invoice: '100',
    startDate: moment().valueOf(),
    endDate: moment().add(3, 'days').valueOf(),
    color: 'green',
    description: 'This is my proyect fixure 10',
}, {
    id: 'p11',
    name:'Proyect 11',
    status: 'doing',
    invoice: '200',
    startDate: moment("2021-03-25").valueOf(),
    endDate: moment("2021-03-29").valueOf(),
    color: 'red',
    description: 'This is my proyect fixure 11',
}, {
    id: 'p12',
    name:'Proyect 12',
    status: 'done',
    invoice: '300',
    startDate: moment("2021-03-25").valueOf(),
    endDate: moment("2021-03-29").valueOf(),
    color: 'blue',
    description: 'This is my proyect fixure 12',
}, {
    id: 'p13',
    name:'Proyect 13',
    status: 'todo',
    invoice: '100',
    startDate: moment("2021-03-25").valueOf(),
    endDate: moment("2021-03-29").valueOf(),
    color: 'green',
    description: 'This is my proyect fixure 13',
}, {
    id: 'p14',
    name:'Proyect 14',
    status: 'doing',
    invoice: '200',
    startDate: moment("2021-03-25").valueOf(),
    endDate: moment("2021-03-29").valueOf(),
    color: 'red',
    description: 'This is my proyect fixure 14',
}, {
    id: 'p15',
    name:'Proyect 15',
    status: 'done',
    invoice: '300',
    startDate: moment("2021-03-25").valueOf(),
    endDate: moment("2021-03-29").valueOf(),
    color: 'blue',
    description: 'This is my proyect fixure 15',
}, {
    id: 'p16',
    name:'Proyect 16',
    status: 'todo',
    invoice: '100',
    startDate: moment("2021-03-25").valueOf(),
    endDate: moment("2021-03-29").valueOf(),
    color: 'green',
    description: 'This is my proyect fixure 16',
}, {
    id: 'p17',
    name:'Proyect 17',
    status: 'doing',
    invoice: '200',
    startDate: moment("2021-03-25").valueOf(),
    endDate: moment("2021-03-29").valueOf(),
    color: 'red',
    description: 'This is my proyect fixure 17',
}, {
    id: 'p18',
    name:'Proyect 18',
    status: 'done',
    invoice: '300',
    startDate: moment("2021-03-25").valueOf(),
    endDate: moment("2021-03-29").valueOf(),
    color: 'blue',
    description: 'This is my proyect fixure 18',
}]